version: '3.7'

services:
  db:
    build: ./docker
    container_name: mysql
    env_file:
      - .env
    cap_add:
      - SYS_NICE
    command:
      - --authentication_policy=mysql_native_password
      - --sha256_password_auto_generate_rsa_keys=ON
      - --auto_generate_certs=ON
      - --pid-file=/var/lib/mysql/mysqld.pid
    volumes:
      - ./data:/var/lib/mysql
      - ./disk:/disk
    ports:
      - 33061:3306
    restart: always
